version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    
  mongo:
    image: "mongo"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
