name: Simple Deploy

on:
  push:
    branches:
      - main  # run the Action on push events to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: TELEGRAM_TOKEN
        script: |
          cd BotFishingGame
          git pull origin main
          cp .env-example .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          sudo ../limited-docker-compose.sh up -d --build
