name: Linting

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
          pip install pylint
          pip install yamllint
          pipenv install --dev

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 \
            --max-line-length=127 --statistics

      # - name: Lint with pylint
      #   run: |
      #     find . -type f -name "*.py" | xargs pylint

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Setup Helm
        uses: azure/setup-helm@v1

      - name: Lint Helm Chart
        run: |
          helm lint ./helm
